services:
  wykop-mirko-saver:
    build: .
    env_file:
      - .env
    restart: on-failure
    volumes:
      - ./output:/app/output
      - ./dist:/app/dist
      - ./node_modules:/app/node_modules
